<header>
    <div align="center">
        <img src="/imgs/bannertop.png">
    </div>
</header>

<ul>
  <li><a class="active" href="index.php"><b>Início</b></a></li>
  <li><a href="contos.php"><b>Contos</b></a></li>
  <li><a href="cantinho_leitor.php"><b>Cantinho do Leitor</b></a></li>
  <li class="dropdown">
    <a href="#" class="dropbtn"><b>Ajudando o Site</b></a>
    <div class="dropdown-content">
      <a href="enviar_conto.php"><b>Envie seu conto</b></a>
      <a href="enviar_foto.php"><b>Envie sua foto</b></a>
      <a href="enviar_sugestao.php"><b>Envie sua sugestão</b></a>
    </div>
  </li>
  <li><a href="quem_somos.php"><b>Quem Somos</b></a></li>
</ul>